[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "mediafile"
author = "Adrian Sampson"
author-email = "adrian@radbox.org"
home-page = "https://github.com/beetbox/mediafile"
description-file = "README.rst"
requires = [
    "six>=1.9",
    "mutagen>=1.45",
]
requires-python = ">=3.6"
classifiers = [
    'Topic :: Multimedia :: Sound/Audio',
    'License :: OSI Approved :: MIT License',
    'Environment :: Web Environment',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: Implementation :: PyPy',
]

[tool.flit.metadata.requires-extra]
test = [
    "tox"
]
