name: Make a release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the new release, just as a number with no prepended "v"'
        required: true

env:
  PYTHON_VERSION: "3.10"
  NEW_VERSION: ${{ inputs.version }}
  NEW_TAG: v${{ inputs.version }}

jobs:
  increment-version:
    name: Bump version, commit and create tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python with uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - name: Bump project version
        run: uv version "${{ env.NEW_VERSION }}"

      - uses: EndBug/add-and-commit@v9
        id: commit_and_tag
        name: Commit the changes and create tag
        with:
          message: "Increment version to ${{ env.NEW_VERSION }}"
          tag: "${{ env.NEW_TAG }} --force"

  build:
    name: Build the distribution package
    runs-on: ubuntu-latest
    needs: increment-version
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.NEW_TAG }}

      - name: Setup Python with uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-cache: true
      - name: Build a binary wheel and a source tarball
        run: uv build

      - name: Store the package
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish distribution ðŸ“¦ to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/mediafile
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution ðŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
